---
- name: Gathering Facts
  hosts: openvpn
  remote_user: ansible
  become: yes

#- name: apply openvpn role
  #hosts: openvpn
  #remote_user: ansible
  #become: yes

  #roles:
  #  - openvpn


- name: Gathering facts
  hosts: nextcloud
  remote_user: fastweb
  become: yes

- name: apply nextcloud role
  hosts: nextcloud
  remote_user: fastweb

  roles:
    - nextcloud

